diseases:
  diabetes:
  - "diabetes"
  - "blood sugar"
  - "insulin"
  - "glucose"
  - "diabetic"
  - "hyperglycemia"
  - "hypoglycemia"
  - "type 1 diabetes"
  - "type 2 diabetes"
  - "gestational diabetes"
  - "diabetic complications"
  - "blood glucose"
  - "insulin resistance"
  - "prediabetes"

  cardiovascular:
  - "heart disease"
  - "cardiovascular"
  - "cardiac"
  - "heart attack"
  - "stroke"
  - "hypertension"
  - "high blood pressure"
  - "coronary"
  - "artery"
  - "cholesterol"
  - "heart failure"
  - "atrial fibrillation"
  - "angina"
  - "heart rhythm"
  - "cardiology"

  cancer:
  - "cancer"
  - "tumor"
  - "oncology"
  - "chemotherapy"
  - "radiation therapy"
  - "malignant"
  - "benign"
  - "carcinoma"
  - "leukemia"
  - "lymphoma"
  - "metastasis"
  - "breast cancer"
  - "lung cancer"
  - "prostate cancer"
  - "skin cancer"
  - "melanoma"

  neurological:
  - "alzheimer"
  - "dementia"
  - "parkinson"
  - "epilepsy"
  - "seizure"
  - "brain"
  - "neurological"
  - "neurology"
  - "migraine"
  - "headache"
  - "memory loss"
  - "cognitive decline"
  - "brain disorder"
  - "nervous system"
  - "neurodegenerative"

  infectious_diseases:
  - "infection"
  - "virus"
  - "bacteria"
  - "flu"
  - "covid"
  - "pneumonia"
  - "tuberculosis"
  - "hepatitis"
  - "hiv"
  - "aids"
  - "malaria"
  - "dengue"
  - "typhoid"
  - "infectious disease"
  - "contagious"
  - "epidemic"
  - "pandemic"

  respiratory:
  - "asthma"
  - "copd"
  - "lung disease"
  - "respiratory"
  - "breathing"
  - "bronchitis"
  - "pneumonia"
  - "lung cancer"
  - "pulmonary"
  - "breathing difficulty"
  - "shortness of breath"
  - "lung infection"
  - "respiratory system"

  digestive:
  - "digestion"
  - "stomach"
  - "intestine"
  - "gastric"
  - "bowel"
  - "diarrhea"
  - "constipation"
  - "acid reflux"
  - "ulcer"
  - "ibs"
  - "crohn"
  - "colitis"
  - "gastroenterology"
  - "gut health"
  - "digestive disorder"

  mental_health:
  - "depression"
  - "anxiety"
  - "stress"
  - "mental health"
  - "psychiatric"
  - "psychology"
  - "bipolar"
  - "schizophrenia"
  - "ptsd"
  - "panic disorder"
  - "ocd"
  - "eating disorder"
  - "addiction"
  - "substance abuse"
  - "therapy"
  - "counseling"

  obesity:
  - "obesity"
  - "overweight"
  - "weight gain"
  - "bmi"
  - "body mass index"
  - "weight management"
  - "childhood obesity"
  - "morbid obesity"
  - "weight loss surgery"
  - "bariatric"

  sleep_disorders:
  - "sleep disorder"
  - "insomnia"
  - "sleep apnea"
  - "sleep health"
  - "sleep deprivation"
  - "sleeplessness"
  - "sleep quality"
  - "sleep pattern"
  - "sleep hygiene"
  - "restless leg"

  hormones:
  - "hormone"
  - "hormonal"
  - "endocrine"
  - "testosterone"
  - "estrogen"
  - "progesterone"
  - "thyroid hormone"
  - "insulin"
  - "cortisol"
  - "hormone imbalance"

  liver:
  - "liver"
  - "hepatic"
  - "liver disease"
  - "liver function"
  - "fatty liver"
  - "cirrhosis"
  - "hepatitis"
  - "liver health"
  - "liver detox"

  kidney:
  - "kidney"
  - "renal"
  - "kidney disease"
  - "kidney function"
  - "kidney stone"
  - "chronic kidney disease"
  - "kidney failure"
  - "dialysis"
  - "nephrology"

  skin:
  - "skin"
  - "dermatology"
  - "acne"
  - "eczema"
  - "psoriasis"
  - "skin cancer"
  - "rash"
  - "skin care"
  - "dermatitis"

  thyroid:
  - "thyroid"
  - "hypothyroid"
  - "hyperthyroid"
  - "thyroid gland"
  - "thyroid function"
  - "thyroid disorder"
  - "goiter"
  - "thyroid hormone"

  eyes_and_ears:
  - "eye"
  - "vision"
  - "ear"
  - "hearing"
  - "eye health"
  - "vision problems"
  - "hearing loss"
  - "eye care"
  - "ophthalmology"
  - "audiology"

  metabolic:
  - "metabolism"
  - "metabolic"
  - "metabolic syndrome"
  - "metabolic disorder"
  - "metabolic health"
  - "metabolic rate"

  reproductive_health:
  - "reproductive health"
  - "fertility"
  - "infertility"
  - "sexual health"
  - "sexual wellness"
  - "reproductive system"
  - "contraception"
  - "family planning"

  inflammation:
  - "inflammation"
  - "inflammatory"
  - "anti-inflammatory"
  - "chronic inflammation"
  - "inflammatory disease"
  - "inflammatory response"

solutions:
  nutrition:
  - "nutrition"
  - "nutrients"
  - "dietary"
  - "nutritional therapy"
  - "nutritional counseling"
  - "diet planning"
  - "nutritional supplements"
  - "nutritional guidance"
  - "vitamins"
  - "minerals"
  - "protein"
  - "carbohydrates"
  - "fat"
  - "fiber"
  - "calories"
  - "macronutrients"
  - "micronutrients"
  - "balanced diet"
  - "healthy eating"
  - "nutritional value"

  fitness:
  - "fitness"
  - "exercise"
  - "workout"
  - "physical activity"
  - "gym"
  - "training"
  - "cardio"
  - "strength training"
  - "yoga"
  - "pilates"
  - "running"
  - "sports"
  - "aerobic"
  - "anaerobic"
  - "muscle building"
  - "endurance"
  - "flexibility"

  lifestyle:
  - "lifestyle"
  - "life style"
  - "way of life"
  - "daily habits"
  - "routine"
  - "living habits"
  - "diet change"
  - "weight loss"
  - "quit smoking"
  - "alcohol reduction"
  - "stress management"
  - "sleep hygiene"
  - "behavior modification"
  - "healthy habits"
  - "lifestyle modification"
  - "self-care"
  - "work-life balance"

  wellness:
  - "wellness"
  - "wellbeing"
  - "holistic health"
  - "mind-body"
  - "self-care"
  - "healthy living"
  - "life balance"
  - "mental wellness"
  - "wellness program"
  - "health monitoring"
  - "alternative medicine"
  - "herbal"
  - "ayurveda"
  - "homeopathy"
  - "acupuncture"
  - "natural remedy"
  - "traditional medicine"
  - "holistic"
  - "complementary medicine"
  - "herbal treatment"
  - "naturopathy"
  - "yoga therapy"
  - "meditation"
  - "mindfulness"

  prevention:
  - "prevention"
  - "preventive"
  - "prevent"
  - "avoiding"
  - "risk prevention"
  - "disease prevention"
  - "health prevention"
  - "screening"
  - "vaccination"
  - "immunization"
  - "checkup"
  - "early detection"
  - "health screening"
  - "prophylaxis"
  - "risk reduction"
  - "health maintenance"
  - "preventive care"
  - "treatment"
  - "therapy"
  - "medication"
  - "drug"
  - "medicine"
  - "prescription"
  - "surgery"
  - "operation"
  - "procedure"
  - "medical intervention"
  - "clinical trial"
  - "pharmaceutical"
  - "remedy"
  - "cure"
  - "healing"
  - "surgical"
  - "minimally invasive"
  - "laparoscopic"
  - "robotic surgery"
  - "transplant"
  - "implant"
  - "bypass"
  - "reconstruction"
  - "removal"
  - "repair"

food:
  "natural food":
  - "natural food"
  - "organic"
  - "natural ingredients"
  - "whole foods"
  - "unprocessed"
  - "farm fresh"
  - "natural eating"
  - "clean eating"
  - "superfood"
  - "antioxidants"
  - "omega-3"
  - "probiotics"
  - "green tea"
  - "berries"
  - "nuts"
  - "seeds"
  - "leafy greens"
  - "whole grains"
  - "fatty fish"
  - "avocado"
  - "quinoa"
  - "chia seeds"

  "organic food":
  - "organic food"
  - "organic farming"
  - "pesticide free"
  - "chemical free"
  - "organic produce"
  - "organic diet"
  - "sustainable food"
  - "eco-friendly food"
  - "non-gmo"
  - "certified organic"

  "processed food":
  - "processed food"
  - "ultra processed"
  - "packaged food"
  - "convenience food"
  - "fast food"
  - "junk food"
  - "artificial ingredients"
  - "food additives"
  - "preservatives"
  - "refined food"
  - "instant food"
  - "canned food"

  "fish and seafood":
  - "fish"
  - "seafood"
  - "salmon"
  - "tuna"
  - "shellfish"
  - "omega-3 fish"
  - "marine food"
  - "aquatic food"
  - "fish nutrition"
  - "fresh fish"
  - "frozen fish"
  - "fish oil"
  - "sea bass"
  - "mackerel"
  - "sardines"

  "food safety":
  - "food safety"
  - "food poisoning"
  - "contamination"
  - "foodborne illness"
  - "expiry date"
  - "food storage"
  - "hygiene"
  - "safe handling"
  - "bacterial contamination"
  - "food recall"
  - "adulteration"
  - "fssai"
  - "food quality"
  - "food standards"
  - "kitchen hygiene"

blogs_and_opinions:
  personal_experiences:
  - "my experience"
  - "personal story"
  - "patient story"
  - "testimonial"
  - "journey"
  - "recovery story"
  - "health journey"
  - "personal account"
  - "first-hand experience"
  - "lived experience"
  - "survivor story"
  - "case study"

  expert_opinions:
  - "expert opinion"
  - "doctor says"
  - "medical expert"
  - "specialist advice"
  - "professional view"
  - "clinical perspective"
  - "medical commentary"
  - "expert analysis"
  - "physician insight"
  - "medical opinion"

  lifestyle_blogs:
  - "lifestyle blog"
  - "health blog"
  - "wellness blog"
  - "fitness blog"
  - "nutrition blog"
  - "daily routine"
  - "healthy living"
  - "wellness tips"
  - "life hacks"
  - "personal tips"

  reviews:
  - "review"
  - "product review"
  - "treatment review"
  - "hospital review"
  - "doctor review"
  - "medication review"
  - "rating"
  - "recommendation"
  - "comparison"
  - "evaluation"

audience:
  women:
  - "women's health"
  - "female health"
  - "pregnancy"
  - "menstruation"
  - "menopause"
  - "breast health"
  - "gynecology"
  - "maternal health"
  - "women's wellness"
  - "female hormones"
  - "pcos"
  - "endometriosis"
  - "osteoporosis"
  - "women"
  - "female"
  - "ladies"

  men:
  - "men's health"
  - "male health"
  - "prostate"
  - "testosterone"
  - "erectile dysfunction"
  - "male fertility"
  - "men's wellness"
  - "male hormones"
  - "men's fitness"
  - "male nutrition"
  - "men"
  - "male"
  - "gentlemen"

  children:
  - "children's health"
  - "pediatric"
  - "child health"
  - "kids health"
  - "infant health"
  - "toddler"
  - "childhood diseases"
  - "pediatrics"
  - "child development"
  - "vaccination schedule"
  - "growth"
  - "immunization"
  - "children"
  - "kids"
  - "child"
  - "baby"
  - "infant"

  teenagers:
  - "teen health"
  - "teenage health"
  - "adolescent health"
  - "teenage wellness"
  - "teen fitness"
  - "puberty"
  - "adolescence"
  - "teen nutrition"
  - "teenage mental health"
  - "teenage development"
  - "teenagers"
  - "teens"
  - "adolescent"
  - "youth"

  seniors:
  - "elderly health"
  - "senior health"
  - "aging"
  - "geriatric"
  - "old age"
  - "senior care"
  - "age-related"
  - "elderly care"
  - "senior wellness"
  - "healthy aging"
  - "seniors"
  - "elderly"
  - "old age health"
  - "geriatric health"
  - "older adults"

  athletes:
  - "sports medicine"
  - "athlete health"
  - "sports nutrition"
  - "exercise physiology"
  - "sports injury"
  - "performance"
  - "endurance"
  - "recovery"
  - "sports supplements"
  - "athletic performance"
  - "athletes"
  - "sportsperson"
  - "fitness enthusiast"
  - "professional sports"

  families:
  - "family health"
  - "household health"
  - "family wellness"
  - "family care"
  - "family medicine"
  - "multi-generational health"
  - "families"
  - "family"
  - "parenting"
  - "childcare"
  - "household"
  - "domestic health"
  - "workplace health"
  - "occupational health"
  - "work stress"
  - "office health"
  - "professional wellness"
  - "work-life balance"
  - "workplace safety"
  - "ergonomics"

trending:
  "gut health":
  - "gut health"
  - "microbiome"
  - "digestive health"
  - "intestinal health"
  - "probiotics"
  - "prebiotics"
  - "gut bacteria"
  - "gut microbiome"
  - "digestive wellness"
  - "gut-brain connection"
  - "leaky gut"
  - "gut flora"

  "mental health":
  - "mental health"
  - "psychological health"
  - "emotional wellness"
  - "mental wellness"
  - "psychological well-being"
  - "mental care"
  - "mental support"
  - "depression"
  - "anxiety"
  - "stress"
  - "psychiatric"
  - "psychology"
  - "bipolar"
  - "ptsd"
  - "therapy"
  - "counseling"

  hormones:
  - "hormones"
  - "hormonal health"
  - "hormone balance"
  - "endocrine health"
  - "hormonal wellness"
  - "hormone"
  - "hormonal"
  - "endocrine"
  - "testosterone"
  - "estrogen"
  - "progesterone"
  - "thyroid hormone"
  - "insulin"
  - "cortisol"
  - "hormone imbalance"

  addiction:
  - "addiction"
  - "substance abuse"
  - "dependency"
  - "addiction recovery"
  - "behavioral addiction"
  - "drug addiction"
  - "alcohol addiction"
  - "smoking addiction"
  - "gambling addiction"

  "sleep health":
  - "sleep health"
  - "sleep wellness"
  - "healthy sleep"
  - "sleep optimization"
  - "sleep quality"
  - "sleep hygiene"
  - "better sleep"
  - "sleep disorder"
  - "insomnia"
  - "sleep apnea"
  - "sleep deprivation"
  - "sleeplessness"
  - "sleep pattern"
  - "restless leg"

  "sexual wellness":
  - "sexual wellness"
  - "sexual health"
  - "intimate health"
  - "sexual well-being"
  - "reproductive wellness"
  - "sexual care"
  - "reproductive health"
  - "fertility"
  - "infertility"
  - "contraception"
  - "family planning"
  - "erectile dysfunction"
  - "libido"


news:
  latest:
  - "latest"
  - "recent"
  - "new"
  - "current"
  - "today"
  - "this week"
  - "recent study"
  - "new research"
  - "latest findings"
  - "recent development"
  - "updated guidelines"
  - "new recommendations"
  - "breaking news"
  - "urgent"
  - "alert"
  - "emergency"
  - "critical"
  - "just in"
  - "developing story"
  - "live updates"
  - "urgent health alert"
  - "health emergency"
  - "immediate action"
  - "health crisis"
  - "pandemic update"
  - "outbreak"
  - "health warning"

  "policy and regulation":
  - "policy and regulation"
  - "health policy"
  - "medical regulation"
  - "healthcare law"
  - "health legislation"
  - "regulatory affairs"
  - "compliance"
  - "health governance"
  - "government policy"
  - "health regulation"
  - "ministry of health"
  - "health department"
  - "public health"
  - "health law"
  - "healthcare policy"
  - "government initiative"
  - "national health"
  - "health budget"

  "govt schemes":
  - "govt schemes"
  - "government schemes"
  - "public health programs"
  - "health initiatives"
  - "welfare schemes"
  - "health insurance"
  - "ayushman bharat"
  - "national health mission"
  - "government scheme"

  international:
  - "international"
  - "global health"
  - "world health"
  - "who"
  - "international cooperation"
  - "global health policy"
  - "cross-border health"
  - "clinical trial"
  - "research study"
  - "medical study"
  - "scientific study"
  - "research findings"
  - "study results"
  - "peer review"
  - "evidence-based"
  - "randomized trial"
  - "medical research"
  - "clinical research"
  - "health alert"
  - "warning"
  - "caution"
  - "advisory"
  - "health notice"
  - "public warning"
  - "safety alert"
  - "health advisory"
  - "medical alert"
  - "urgent notice"