# New international and Indian health categories to add to the existing file
# Add this at the end of your existing category_keywords.yml

international_health:
  medical_journals:
  - "journal"
  - "research paper"
  - "study"
  - "clinical trial"
  - "medical journal"
  - "lancet"
  - "bmj"
  - "nejm"
  - "nature medicine"
  - "jama"
  - "scientific publication"
  - "peer-reviewed"
  - "medicine publication"
  
  global_health_organizations:
  - "world health organization"
  - "who"
  - "unicef"
  - "red cross"
  - "doctors without borders"
  - "médecins sans frontières"
  - "msf"
  - "united nations"
  - "global health"
  - "international health"
  - "pandemic response"
  - "world bank health"
  - "who regional office"
  
  european_health:
  - "european health"
  - "nhs"
  - "national health service"
  - "european medicine agency"
  - "ema"
  - "european union health"
  - "uk health"
  - "german health"
  - "french health"
  - "italian health"
  - "spanish health"
  - "nordic healthcare"
  
  americas_health:
  - "cdc"
  - "centers for disease control"
  - "fda"
  - "nih"
  - "national institutes of health"
  - "american health"
  - "canadian health"
  - "paho"
  - "pan american health"
  - "latin american health"
  - "south american health"
  - "brazilian health"
  
  asia_pacific_health:
  - "asian health"
  - "pacific health"
  - "australian health"
  - "japanese health"
  - "korean health"
  - "chinese health"
  - "southeast asian"
  - "thai health"
  - "singapore health"
  - "malaysian health"
  - "indonesian health"
  - "philippines health"
  
  africa_middle_east_health:
  - "african health"
  - "middle east health"
  - "african cdc"
  - "afro who"
  - "emro"
  - "eastern mediterranean"
  - "african union health"
  - "south african health"
  - "nigerian health"
  - "kenyan health"
  - "egyptian health"
  - "saudi health"
  - "uae health"

indian_health:
  government_health:
  - "ministry of health"
  - "mohfw"
  - "aiims"
  - "all india institute of medical sciences"
  - "icmr"
  - "indian council of medical research"
  - "niti aayog health"
  - "national health mission"
  - "nhm"
  - "ayushman bharat"
  - "pradhan mantri jan arogya yojana"
  - "pm-jay"
  - "health policy india"
  - "national health authority"
  
  ayurveda_traditional_medicine:
  - "ayurveda"
  - "ayush"
  - "traditional medicine"
  - "yoga"
  - "homeopathy"
  - "unani"
  - "siddha"
  - "naturopathy"
  - "herbal medicine"
  - "indian medicine"
  - "ayurvedic treatment"
  - "traditional healing"
  
  indian_medical_research:
  - "indian medical"
  - "indian research"
  - "indian study"
  - "indian clinical trial"
  - "indian journal"
  - "indian medicine"
  - "indian public health"
  - "indian epidemiology"
  - "indian health data"
  - "indian medical association"
  - "ima"
  - "indian healthcare research"
  
  public_health_india:
  - "public health india"
  - "indian public health"
  - "health infrastructure india"
  - "rural healthcare india"
  - "urban healthcare india"
  - "sanitation india"
  - "clean india"
  - "swachh bharat"
  - "water quality india"
  - "indian health services"
  - "indian primary care"
  - "indian healthcare delivery"
  
  indian_healthcare_industry:
  - "indian hospitals"
  - "indian pharmaceutical"
  - "indian medical devices"
  - "indian health insurance"
  - "indian telemedicine"
  - "indian health tech"
  - "indian health startup"
  - "indian medical tourism"
  - "apollo hospital"
  - "fortis"
  - "max healthcare"
  - "medanta"
  - "indian healthcare company"
