# Men's health subcategory keywords to enhance the existing audience category

audience:
  men:
  - "men's health"
  - "male health"
  - "men health"
  - "prostate"
  - "testosterone"
  - "erectile dysfunction"
  - "impotence"
  - "male fertility"
  - "sperm count"
  - "sperm health"
  - "testicular"
  - "testicular cancer"
  - "prostate cancer"
  - "male pattern baldness"
  - "hair loss men"
  - "baldness"
  - "male hormones"
  - "low-t"
  - "low testosterone"
  - "andropause"
  - "male menopause"
  - "men's fitness"
  - "men's nutrition"
  - "male reproductive health"
  - "men's mental health"
  - "male depression"
  - "men's sexual health"
  - "father's health"
  - "beard health"
  - "beard growth"
  - "male wellness"
  - "men's preventive care"
  - "men's medical screening"
  - "male breast cancer"
  - "gynecomastia"
  - "men's weight loss"
  - "men's muscle health"
  - "men's cardiovascular health"
  - "male urinary health"
  - "benign prostatic hyperplasia"
  - "bph"
  - "prostatitis"
  - "men's skin health"
  - "men's aging"
